apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-app-c
  namespace: authorization-policy
  labels:
    account: app-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-c
  namespace: authorization-policy
spec:
  selector:
    matchLabels:
      app: app-c
  template:
    metadata:
      labels:
        app: app-c
    spec:
      serviceAccountName: sa-app-c
      containers:
        - name: app-c
          image: algab/poc-istio-authorization-policy-app-c:1.0
          env:
            - name: APP_A
              value: http://service-app-a.authorization-policy.svc.cluster.local
            - name: APP_B
              value: http://service-app-b.authorization-policy.svc.cluster.local
          resources:
            limits:
              memory: "32Mi"
              cpu: "125m"
          ports:
            - containerPort: 3002
