apiVersion: "security.istio.io/v1beta1"
kind: "AuthorizationPolicy"
metadata:
  name: "policy-app-b"
  namespace: authorization-policy
spec:
  selector:
    matchLabels:
      app: app-b
  action: DENY
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/authorization-policy/sa/sa-app-c"]
      to:
        - operation:
            methods: ["*"]
